CREATE TABLE SP_VENDOR(
VENDOR_ID BIGSERIAL PRIMARY KEY,
VENDOR_CODE VARCHAR(5),
VENDOR_DESC VARCHAR(100),
TRADING_PARTNER_ID VARCHAR(5),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);

CREATE TABLE SP_ORDER(
ORDER_ID BIGSERIAL PRIMARY KEY,
PO_NUMBER VARCHAR(50) NOT NULL,
ORDER_TYPE VARCHAR(2),
VENDOR_CODE VARCHAR(5),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP

);
ALTER TABLE SP_ORDER
    ADD CONSTRAINT SP_ORDER_UNIQUE UNIQUE (po_number, order_type, vendor_code);
    
CREATE TABLE SP_PART (
PART_ID BIGSERIAL  PRIMARY KEY,
ORDER_ID bigint,
PART_NUMBER VARCHAR(50),
LINE_ITEM_NUMBER VARCHAR(50),
DDD timestamp,
PART_DESC VARCHAR(200),
ORDER_QUANTITY INTEGER,
OUTSTANDING_QUANTITY INTEGER,
VENDOR_PART_NUMBER VARCHAR(50),
DIRECT_SHIP VARCHAR(2),
HOME_POSITION VARCHAR(50),
TRANSMISSION_DATE TIMESTAMP,
ORDER_REF_NUMBER VARCHAR(50),
DEALER VARCHAR(50),
STATUS VARCHAR(50),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP,
CONTAINER_ID VARCHAR(50),
SERIAL_NUMBER VARCHAR(50),
SUB_PART_NUMBER bigint
);
ALTER TABLE SP_PART
    ADD CONSTRAINT SP_PART_UNIQUE UNIQUE (part_number, line_item_number, ddd);

CREATE TABLE SP_ROUTE_PATH(
ROUTE_PATH_ID BIGSERIAL  PRIMARY KEY,
ROUTE_SEQ INTEGER,
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_SHIPMENT(
SHIPMENT_ID BIGSERIAL  PRIMARY KEY,
ROUTE VARCHAR(10),
RUN VARCHAR(10),
SHIP_DATE TIMESTAMP,
TRAILER VARCHAR(100),
DRIVER_FIRST_NAME VARCHAR(100),
DRIVER_LAST_NAME VARCHAR(100),
SCAC_CODE VARCHAR(10),
SUPPLIER_FIRST_NAME VARCHAR(100),
SUPPLIER_LAST_NAME VARCHAR(100),
TRACKING_NUMBER VARCHAR(100),
CONFIRMAATION_NUMBER VARCHAR(100),
STATUS VARCHAR(50),
GEO_LONGITUDE VARCHAR(100),
GEO_LATTITUDE VARCHAR(100),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_CASE(
CASE_ID BIGSERIAL  PRIMARY KEY,
CASE_NUMBER VARCHAR(100),
CONFIRMATION_NUMBER VARCHAR(100),
STATUS VARCHAR(50),
SHIPMENT_ID bigint,
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_PART_TRANS(
PART_TRANS_ID BIGSERIAL PRIMARY KEY,
PART_ID bigint,
SUPPLIER_TOTAL INTEGER, 
TRANSMISSION_DATE TIMESTAMP,
SERIAL_NUMBER VARCHAR(100),
CASE_ID bigint,
ORDER_ID bigint,
STATUS VARCHAR(50),
FULLFILLED_QUANTITY INTEGER,
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_ROUTE_PATH_NODE(
ROUTE_PATH_NODE_ID BIGSERIAL  PRIMARY KEY,
ROUTE_PATH_ID bigint,
FACILITY INTEGER,
CASE_ID  bigint,
SHIPMENT_ID bigint,
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_PALLET_SIZE_LIMIT(
ID BIGSERIAL PRIMARY KEY,
DESTINATION_FD VARCHAR(50),
HOME_POSITION VARCHAR(50),
LENGTH VARCHAR(50),
WIDTH VARCHAR(50),
HEIGHT VARCHAR(50),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_SERIAL_NUMBER(
SERIAL_ID BIGSERIAL PRIMARY KEY,
PART_TRANS_ID bigint,
SERIAL_NUMBER VARCHAR(50),
MODIFIED_BY VARCHAR(50),
MODIFIED_DATE TIMESTAMP
);


CREATE TABLE SP_EXCEPTION(
EXCEPTION_ID BIGSERIAL  PRIMARY KEY,
CASE_ID bigint,
EXCEPTION_CODE VARCHAR(50),
COMMENTS VARCHAR(50)
);