DELETE FROM SPADM.SP_EXCEPTION;

DELETE FROM SPADM.SP_VENDOR;

DELETE FROM SPADM.SP_ORDER;

DELETE FROM SPADM.SP_PART;

DELETE FROM SPADM.SP_CASE;

DELETE FROM SPADM.SP_PART_TRANS;

DELETE FROM SPADM.SP_ROUTE_PATH;

DELETE FROM SPADM.SP_ROUTE_PATH_NODE;

DELETE FROM SPADM.SP_SERIAL_NUMBER;

DELETE FROM SPADM.SP_SHIPMENT;

DELETE FROM SPADM.SP_VENDOR;